# Generated by Django 5.0 on 2023-12-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customer_id_customer_birth_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
    ]
